version: "3.7"

services:
  app:
    image: vote:latest
    volumes:
      - ./votedir:/vote
    working_dir: /vote
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - back-tier
  redis:
    image: redis:latest
    container_name: voteredis
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports: 
      - "6379:6379"
    networks:
      - back-tier
networks:
  back-tier: